name: deploy
on:
  workflow_dispatch:

env:
  CI: false

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Deploy
        run: npm run deploy
        working-directory: frontend
